EXERCISE_CONFIGS = {
    "03_Uvod_HZD": {
        "name": "Úvod HZD – Cvičení 3",
        "answer_key_file": "03_Uvod_HZD.xlsx",
        "tasks": [
            {
                "id": "task1",
                "name": "Adresy buněk",
                "sheet": "Úkol 1",
                "answer_col": "G",
                "answer_row_start": 17,
                "answer_row_end": 26,
                "key_sheet": "Klíč",
                "key_col": "A",
                "key_row_start": 2,
                "key_row_end": 11,
                "max_points": 10,
                "comparison": "mixed",
                "requires_formula": False,  # Úkol 1 = text/čísla, vzorec není povinný
            },
            {
                "id": "task2",
                "name": "Vzorce s operátory",
                "sheet": "Úkol 2",
                "answer_col": "D",
                "answer_row_start": 9,
                "answer_row_end": 20,
                "key_sheet": "Klíč",
                "key_col": "A",
                "key_row_start": 20,
                "key_row_end": 31,
                "max_points": 12,
                "comparison": "numeric",
                "requires_formula": True,
            },
            {
                "id": "task3",
                "name": "Vzorce s odkazy",
                "sheet": "Úkol 3",
                "answer_col": "E",
                "answer_row_start": 15,
                "answer_row_end": 22,
                "key_sheet": "Klíč",
                "key_col": "A",
                "key_row_start": 40,
                "key_row_end": 47,
                "max_points": 8,
                "comparison": "numeric",
                "requires_formula": True,
            },
            {
                "id": "task4",
                "name": "Funkce SUMA",
                "sheet": "Úkol 4",
                "answer_col": "H",
                "answer_row_start": 9,
                "answer_row_end": 16,
                "key_sheet": "Klíč",
                "key_col": "A",
                "key_row_start": 60,
                "key_row_end": 67,
                "max_points": 8,
                "comparison": "numeric",
                "requires_formula": True,
            },
            {
                "id": "task5",
                "name": "Statistické funkce",
                "sheet": "Úkol 5",
                "answer_col": "D",
                "answer_col2": "E",   # Druhý sloupec — oba musí být vzorce
                "answer_row_start": 19,
                "answer_row_end": 28,
                "key_sheet": "Klíč",
                "key_col": "A",
                "key_row_start": 80,
                "key_row_end": 89,
                "max_points": 10,
                "comparison": "numeric",
                "requires_formula": True,
            },
            {
                "id": "task6",
                "name": "Komplexní úloha",
                "sheet": "Úkol 6",
                "answer_col": "F",
                "answer_row_start": 20,
                "answer_row_end": 27,
                "key_sheet": "Klíč",
                "key_col": "A",
                "key_row_start": 100,
                "key_row_end": 107,
                "max_points": 8,
                "comparison": "numeric",
                "requires_formula": True,
            },
        ],
    },
}
